# Generated by Django 2.1.4 on 2019-01-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='friend',
        ),
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_member_friends_+', to='base.Member'),
        ),
    ]
