# Generated by Django 2.1.4 on 2019-01-27 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190127_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 18, 43, 47, 33827, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 18, 43, 47, 32961, tzinfo=utc)),
        ),
    ]
