# Generated by Django 2.1.4 on 2019-01-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190128_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='sent_requests', to='base.Member'),
        ),
    ]
