# Generated by Django 2.1.4 on 2019-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_member_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.IntegerField(default=240),
        ),
        migrations.AddField(
            model_name='member',
            name='width',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='profile_pics', width_field='width'),
        ),
    ]
