# Generated by Django 2.1.4 on 2019-02-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190202_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='height',
        ),
        migrations.RemoveField(
            model_name='member',
            name='width',
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
