# Generated by Django 2.1.4 on 2019-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='users',
            field=models.ManyToManyField(blank=True, to='base.Member'),
        ),
    ]
