# Generated by Django 2.1.4 on 2019-02-01 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20190201_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
