# Generated by Django 2.1.4 on 2019-02-02 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
